const products = [
  {
    image: "assets/ring-item.png",
    alt: 'ring',
    name: "HANDMADE PEARL RING",
    priceCents: 29999,
    manufacturer: 'Nadia Khan',
    manufacturerCountry: 'Bangladesh',
  },
  {
    image: "assets/pocket-watch-item.png",
    alt: 'golden-watch',
    name: "GOLDEN WATCH",
    priceCents: 19999,
    manufacturer: 'Hui Dixon',
    manufacturerCountry: 'China',
  },
  {
    image: "assets/earrings-item.png",
    alt: 'earrings',
    name: "HANDMADE EARRINGS",
    priceCents: 9999,
    manufacturer: 'Karna Bhardwaj',
    manufacturerCountry: 'India',
  },
  {
    image: "assets/diamond-ring-item.png",
    alt: 'diamond-ring',
    name: "HANDMADE DIAMOND RING",
    priceCents: 99999,
    manufacturer: 'Hui Dixon',
    manufacturerCountry: 'China',
  },
  {
    image: "assets/bracelet-item.png",
    alt: 'bracelet',
    name: "BRACELET",
    priceCents: 29999,
    manufacturer: 'Hui Dixon',
    manufacturerCountry: 'China',
  },
  {
    image: "assets/diamond-earrings-item.png",
    alt: 'diamond-earrings',
    name: "HANDMADE DIAMOND EARRINGS",
    priceCents: 19999,
    manufacturer: 'Nadia Khan',
    manufacturerCountry: 'Bangladesh',
  },
  {
    image: "assets/golden-bracelet-item.png",
    alt: 'golden-bracelet',
    name: "GOLDEN BRACELET",
    priceCents: 49999,
    manufacturer: 'Nadia Khan',
    manufacturerCountry: 'Bangladesh',
  },
  {
    image: "assets/necklace-item.png",
    alt: 'necklace',
    name: "NECKLACE",
    priceCents: 19999,
    manufacturer: 'Hui Dixon',
    manufacturerCountry: 'China',
  },
  {
    image: "assets/silver-ring-item.png",
    alt: 'silver-ring',
    name: "SILVER RING",
    priceCents: 49999,
    manufacturer: 'Karna Bhardwaj',
    manufacturerCountry: 'India',
  },
];